# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\RaceWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QPushButton, QHBoxLayout, QVBoxLayout, QBoxLayout, QGridLayout, QLabel, QApplication, QGraphicsDropShadowEffect
import time

class Ui_RaceWidget(QWidget):
    Current_RaceTime = 0
    Current_LapTime = 0
    Current_Last_LapTime = 0
    Current_Best_LapTime = 0

    def __init__(self):
        super().__init__()
        self.setFixedSize(475, 180)
        self.setupUi(self)
        self.setStyleSheet("background-color: black; color: white;")
        self.UpdateTimer = QtCore.QTimer()
        self.UpdateTimer.timeout.connect(self.UpdateDisplays)
        self.UpdateTimer.start(100)

    def OnTelemetryData(self, data):
        if data['is_race_on'] == 1.0:
            self.Current_RaceTime = data['cur_race_time']
            self.Current_LapTime = data['cur_lap_time']
            self.Current_Last_LapTime = data['last_lap_time']
            self.Current_Best_LapTime = data['best_lap_time']

    def FormatFromSeconds(self, seconds):
        return time.strftime('%H:%M:%S', time.gmtime(seconds))


    def UpdateDisplays(self):
        self.RaceTime_Label.setText(self.FormatFromSeconds(self.Current_RaceTime))
        self.LapTime_Label.setText(self.FormatFromSeconds(self.Current_LapTime))
        self.BestLap_Label.setText(self.FormatFromSeconds(self.Current_Best_LapTime))
        self.LastLap_Label.setText(self.FormatFromSeconds(self.Current_Last_LapTime))

    def setupUi(self, RaceWidget):
        RaceWidget.setObjectName("RaceWidget")
        self.label_2 = QtWidgets.QLabel(RaceWidget)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(RaceWidget)
        self.label_3.setGeometry(QtCore.QRect(240, 100, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(RaceWidget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(RaceWidget)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.RaceTime_Label = QtWidgets.QLabel(RaceWidget)
        self.RaceTime_Label.setGeometry(QtCore.QRect(10, 30, 230, 60))
        font = QtGui.QFont()
        font.setFamily("LCD")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.RaceTime_Label.setFont(font)
        self.RaceTime_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.RaceTime_Label.setObjectName("RaceTime_Label")
        self.LapTime_Label = QtWidgets.QLabel(RaceWidget)
        self.LapTime_Label.setGeometry(QtCore.QRect(240, 30, 230, 60))
        font = QtGui.QFont()
        font.setFamily("LCD")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.LapTime_Label.setFont(font)
        self.LapTime_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.LapTime_Label.setObjectName("LapTime_Label")
        self.LastLap_Label = QtWidgets.QLabel(RaceWidget)
        self.LastLap_Label.setGeometry(QtCore.QRect(10, 120, 230, 60))
        font = QtGui.QFont()
        font.setFamily("LCD")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.LastLap_Label.setFont(font)
        self.LastLap_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.LastLap_Label.setObjectName("LastLap_Label")
        self.BestLap_Label = QtWidgets.QLabel(RaceWidget)
        self.BestLap_Label.setGeometry(QtCore.QRect(240, 120, 230, 60))
        font = QtGui.QFont()
        font.setFamily("LCD")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.BestLap_Label.setFont(font)
        self.BestLap_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.BestLap_Label.setObjectName("BestLap_Label")

        self.retranslateUi(RaceWidget)
        QtCore.QMetaObject.connectSlotsByName(RaceWidget)

    def retranslateUi(self, RaceWidget):
        _translate = QtCore.QCoreApplication.translate
        RaceWidget.setWindowTitle(_translate("RaceWidget", "Race Information"))
        self.label_2.setText(_translate("RaceWidget", "LAP TIME"))
        self.label_3.setText(_translate("RaceWidget", "BEST LAP TIME"))
        self.label_4.setText(_translate("RaceWidget", "RACE TIME"))
        self.label_5.setText(_translate("RaceWidget", "LAST LAP TIME"))
        self.RaceTime_Label.setText(_translate("RaceWidget", "00:00.000"))
        self.LapTime_Label.setText(_translate("RaceWidget", "00:00.000"))
        self.LastLap_Label.setText(_translate("RaceWidget", "00:00.000"))
        self.BestLap_Label.setText(_translate("RaceWidget", "00:00.000"))
