# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\WheelsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QPushButton, QHBoxLayout, QVBoxLayout, QBoxLayout, QGridLayout, QLabel, QApplication, QGraphicsDropShadowEffect
from ColorHelper import ColorInterpolate

class Ui_WheelsWidget(QWidget):
    def __init__(self):
        super().__init__()
        self.setFixedSize(285, 335)
        self.setupUi(self)

    def setupUi(self, WheelsWidget):
        WheelsWidget.setObjectName("WheelsWidget")
        WheelsWidget.resize(285, 335)
        self.RL_Suspension_Bar = QtWidgets.QProgressBar(WheelsWidget)
        self.RL_Suspension_Bar.setGeometry(QtCore.QRect(100, 170, 20, 160))
        self.RL_Suspension_Bar.setMaximum(100)
        #self.RL_Suspension_Bar.setProperty("value", 8)
        self.RL_Suspension_Bar.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.RL_Suspension_Bar.setTextVisible(False)
        self.RL_Suspension_Bar.setOrientation(QtCore.Qt.Vertical)
        self.RL_Suspension_Bar.setObjectName("RL_Suspension_Bar")
        self.RR_Wheel_Frame = QtWidgets.QFrame(WheelsWidget)
        self.RR_Wheel_Frame.setGeometry(QtCore.QRect(190, 170, 90, 160))
        self.RR_Wheel_Frame.setStyleSheet(".QFrame{ background-color: green; border: 1px solid black; border-radius: 10px;}")
        self.RR_Wheel_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RR_Wheel_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RR_Wheel_Frame.setObjectName("RR_Wheel_Frame")
        self.RR_Wheel_Temp = QtWidgets.QLabel(self.RR_Wheel_Frame)
        self.RR_Wheel_Temp.setGeometry(QtCore.QRect(0, 60, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.RR_Wheel_Temp.setFont(font)
        self.RR_Wheel_Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.RR_Wheel_Temp.setObjectName("RR_Wheel_Temp")
        self.RL_Wheel_Frame = QtWidgets.QFrame(WheelsWidget)
        self.RL_Wheel_Frame.setGeometry(QtCore.QRect(5, 170, 90, 160))
        self.RL_Wheel_Frame.setStyleSheet(".QFrame{ background-color: green; border: 1px solid black; border-radius: 10px;}")
        self.RL_Wheel_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RL_Wheel_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RL_Wheel_Frame.setObjectName("RL_Wheel_Frame")
        self.RL_Wheel_Temp = QtWidgets.QLabel(self.RL_Wheel_Frame)
        self.RL_Wheel_Temp.setGeometry(QtCore.QRect(0, 60, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.RL_Wheel_Temp.setFont(font)
        self.RL_Wheel_Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.RL_Wheel_Temp.setObjectName("RL_Wheel_Temp")
        self.FL_Wheel_Frame = QtWidgets.QFrame(WheelsWidget)
        self.FL_Wheel_Frame.setGeometry(QtCore.QRect(5, 5, 90, 160))
        self.FL_Wheel_Frame.setStyleSheet(".QFrame{ background-color: green; border: 1px solid black; border-radius: 10px;}")
        self.FL_Wheel_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FL_Wheel_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FL_Wheel_Frame.setObjectName("FL_Wheel_Frame")
        self.FL_Wheel_Temp = QtWidgets.QLabel(self.FL_Wheel_Frame)
        self.FL_Wheel_Temp.setGeometry(QtCore.QRect(0, 60, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.FL_Wheel_Temp.setFont(font)
        self.FL_Wheel_Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.FL_Wheel_Temp.setObjectName("FL_Wheel_Temp")
        self.FR_Suspension_Bar = QtWidgets.QProgressBar(WheelsWidget)
        self.FR_Suspension_Bar.setGeometry(QtCore.QRect(165, 5, 20, 160))
        self.FR_Suspension_Bar.setMaximum(100)
        #self.FR_Suspension_Bar.setProperty("value", 8)
        self.FR_Suspension_Bar.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.FR_Suspension_Bar.setTextVisible(False)
        self.FR_Suspension_Bar.setOrientation(QtCore.Qt.Vertical)
        self.FR_Suspension_Bar.setObjectName("FR_Suspension_Bar")
        self.FR_Wheel_Frame = QtWidgets.QFrame(WheelsWidget)
        self.FR_Wheel_Frame.setGeometry(QtCore.QRect(190, 5, 90, 160))
        self.FR_Wheel_Frame.setStyleSheet(".QFrame{ background-color: green; border: 1px solid black; border-radius: 10px;}")
        self.FR_Wheel_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FR_Wheel_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FR_Wheel_Frame.setObjectName("FR_Wheel_Frame")
        self.FR_Wheel_Temp = QtWidgets.QLabel(self.FR_Wheel_Frame)
        self.FR_Wheel_Temp.setGeometry(QtCore.QRect(0, 60, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.FR_Wheel_Temp.setFont(font)
        self.FR_Wheel_Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.FR_Wheel_Temp.setObjectName("FR_Wheel_Temp")
        self.FL_Suspension_Bar = QtWidgets.QProgressBar(WheelsWidget)
        self.FL_Suspension_Bar.setGeometry(QtCore.QRect(100, 5, 20, 160))
        self.FL_Suspension_Bar.setMaximum(100)
        #self.FL_Suspension_Bar.setProperty("value", 8)
        self.FL_Suspension_Bar.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.FL_Suspension_Bar.setTextVisible(False)
        self.FL_Suspension_Bar.setOrientation(QtCore.Qt.Vertical)
        self.FL_Suspension_Bar.setObjectName("FL_Suspension_Bar")
        self.RR_Suspension_Bar = QtWidgets.QProgressBar(WheelsWidget)
        self.RR_Suspension_Bar.setGeometry(QtCore.QRect(165, 170, 20, 160))
        self.RR_Suspension_Bar.setMaximum(100)
        #self.RR_Suspension_Bar.setProperty("value", 8)
        self.RR_Suspension_Bar.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.RR_Suspension_Bar.setTextVisible(False)
        self.RR_Suspension_Bar.setOrientation(QtCore.Qt.Vertical)
        self.RR_Suspension_Bar.setObjectName("RR_Suspension_Bar")

        self.AddShadowToLabel(self.RR_Wheel_Temp)
        self.AddShadowToLabel(self.RL_Wheel_Temp)
        self.AddShadowToLabel(self.FR_Wheel_Temp)
        self.AddShadowToLabel(self.FL_Wheel_Temp)
        self.retranslateUi(WheelsWidget)
        QtCore.QMetaObject.connectSlotsByName(WheelsWidget)

    def AddShadowToLabel(self, label):
        shadow = QGraphicsDropShadowEffect()
        # setting blur radius
        shadow.setBlurRadius(1)
        shadow.setOffset(0, 0)
        label.setGraphicsEffect(shadow)


    def retranslateUi(self, WheelsWidget):
        _translate = QtCore.QCoreApplication.translate
        WheelsWidget.setWindowTitle(_translate("WheelsWidget", "Form"))
        self.RR_Wheel_Temp.setText(_translate("WheelsWidget", "200C"))
        self.RL_Wheel_Temp.setText(_translate("WheelsWidget", "200C"))
        self.FL_Wheel_Temp.setText(_translate("WheelsWidget", "200C"))
        self.FR_Wheel_Temp.setText(_translate("WheelsWidget", "200C"))
        self.FR_Wheel_Temp.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.FL_Wheel_Temp.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.RL_Wheel_Temp.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.RR_Wheel_Temp.setStyleSheet("background-color: rgba(0,0,0,0%)")

    def SetSuspensionBarColorForValue(self, suspensionBar, value):
        if value > 75:
            suspensionBar.setStyleSheet("QProgressBar::chunk { background-color: #cc0000; }")
        elif value >= 50:
            suspensionBar.setStyleSheet("QProgressBar::chunk { background-color: #05B8CC; }")
        elif value < 50:
            suspensionBar.setStyleSheet("QProgressBar::chunk { background-color: #0000ff; }")
        elif value <= 25:
            suspensionBar.setStyleSheet("QProgressBar::chunk { background-color: #000019; }")

    def UpdateForData(self, data):
        # wheel temps
        self.FL_Wheel_Temp.setText(str(int(data['tire_temp_FL']))+"°C")
        self.FR_Wheel_Temp.setText(str(int(data['tire_temp_FR']))+"°C")
        self.RL_Wheel_Temp.setText(str(int(data['tire_temp_RL']))+"°C")
        self.RR_Wheel_Temp.setText(str(int(data['tire_temp_RR']))+"°C")
        # wheel temps stylesheet
        FL_Hex_Color = ColorInterpolate(int(data['tire_temp_FL']), 'blue', 'gray', 'orange', 'yellow', 135, 165, 225, 250, 280, 320)
        FR_Hex_Color = ColorInterpolate(int(data['tire_temp_FR']), 'blue', 'gray', 'orange', 'yellow', 135, 165, 225, 250, 280, 320)
        RL_Hex_Color = ColorInterpolate(int(data['tire_temp_RL']), 'blue', 'gray', 'orange', 'yellow', 135, 165, 225, 250, 280, 320)
        RR_Hex_Color = ColorInterpolate(int(data['tire_temp_RR']), 'blue', 'gray', 'orange', 'yellow', 135, 165, 225, 250, 280, 320)
        self.FL_Wheel_Frame.setStyleSheet(".QFrame{ background-color: "+FL_Hex_Color+"; border: 1px dotted black; border-radius: 10px;}")
        self.FR_Wheel_Frame.setStyleSheet(".QFrame{ background-color: "+FR_Hex_Color+"; border: 1px dotted black; border-radius: 10px;}")
        self.RL_Wheel_Frame.setStyleSheet(".QFrame{ background-color: "+RL_Hex_Color+"; border: 1px dotted black; border-radius: 10px;}")
        self.RR_Wheel_Frame.setStyleSheet(".QFrame{ background-color: "+RR_Hex_Color+"; border: 1px dotted black; border-radius: 10px;}")
        # suspension
        self.SetSuspensionBarColorForValue(self.FL_Suspension_Bar, int(data['norm_suspension_travel_FL'] * 100.0))
        self.SetSuspensionBarColorForValue(self.FR_Suspension_Bar, int(data['norm_suspension_travel_FR'] * 100.0))
        self.SetSuspensionBarColorForValue(self.RL_Suspension_Bar, int(data['norm_suspension_travel_RL'] * 100.0))
        self.SetSuspensionBarColorForValue(self.RR_Suspension_Bar, int(data['norm_suspension_travel_RR'] * 100.0))
        self.FL_Suspension_Bar.setValue(int(data['norm_suspension_travel_FL'] * 100.0))
        self.FR_Suspension_Bar.setValue(int(data['norm_suspension_travel_FR'] * 100.0))
        self.RL_Suspension_Bar.setValue(int(data['norm_suspension_travel_RL'] * 100.0))
        self.RR_Suspension_Bar.setValue(int(data['norm_suspension_travel_RR'] * 100.0))
        QApplication.processEvents() 